export const SEARCH_BY_CATEGORY = {
  type: [
    'normal',
    'fighting',
    'flying',
    'poison',
    'ground',
    'rock',
    'bug',
    'ghost',
    'steel',
    'fire',
    'water',
    'grass',
    'electric',
    'psychic',
    'ice',
    'dragon',
    'dark',
    'fairy',
    'unknown',
    'shadow',
  ],
  'pokemon-color': ['black', 'blue', 'brown', 'gray', 'green', 'pink', 'purple', 'red', 'white', 'yellow'],
  'pokemon-habitat': [
    'cave',
    'forest',
    'grassland',
    'mountain',
    'rare',
    'rough-terrain',
    'sea',
    'urban',
    'waters-edge',
  ],
} as const;

export const MAJOR_CATEGORY_OF_SEARCH = Object.keys(SEARCH_BY_CATEGORY);
